name: trading_intelligence
description: 999 Trading Intelligence
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.6.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  supabase_flutter: ^2.17.1
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/branding/999_trading_intelligence_icon.png
  uses-material-design: true
